version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "rodrigobastosv"
    assignees:
      - "rodrigobastosv"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "flutter"
        versions: ["<3.0.0"]
