name: fancy_credit_card_input
description: "A new Flutter package project."
version: 1.0.0
homepage: https://github.com/rodrigobastosv/fancy_credit_card_input

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  mask_text_input_formatter: ^2.9.0
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <6.0.0"

flutter:
  assets:
    - icons/
  